#!/bin/sh
GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
mkdir -p "$GUIX_EXTRA_PROFILES"/desktop # if it does not exist yet
guix package --fallback --manifest=$HOME/.config/guix/manifests/desktop.scm --profile="$GUIX_EXTRA_PROFILES"/desktop/desktop
