#!/bin/sh
GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
mkdir -p "$GUIX_EXTRA_PROFILES"/doom-emacs # if it does not exist yet
guix package --manifest=$HOME/.config/guix/manifests/doom-emacs.scm --profile="$GUIX_EXTRA_PROFILES"/doom-emacs/doom-emacs
