#!/home/k8x1d/.guix-profile/bin/bash
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

flatpak install flathub --user com.sindresorhus.Caprine
flatpak install flathub --user us.zoom.Zoom
