#!/bin/sh
GUIX_EXTRA_PROFILES=$HOME/.guix-extra-profiles
mkdir -p "$GUIX_EXTRA_PROFILES"/python # if it does not exist yet
guix package --manifest=$HOME/.config/guix/manifests/python.scm --profile="$GUIX_EXTRA_PROFILES"/python/python
