#!/bin/sh
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
		$(LANGUAGE=fr $(which signal-desktop) --ozone-platform=wayland --enable-features=WaylandWindowDecorations)
else
		LANGUAGE=fr $(which signal-desktop)
fi
